#!/system/xbin/busybox sh

echo 249600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1209600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo smartassV2 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
