#!/system/bin/sh
miversion='3.7.11'
mitime='czw, 11 lip 2013, 12:41:17'
miutc='1373539277'
miota='20130711-1241'
cp -f /system/build.prop /tmp/build.prop
chmod 755 /tmp/build.prop
sed -i -e "s/ro\.build\.date=.*/ro\.build\.date=$mitime/" /tmp/build.prop
sed -i -e "s/ro\.build\.date\.utc=.*/ro\.build\.date\.utc=$miutc/" /tmp/build.prop
sed -i -e "s/ro\.build\.version\.incremental=.*/ro\.build\.version\.incremental=$miversion/" /tmp/build.prop
sed -i -e "s/updater\.time=.*/updater\.time=$miota/" /tmp/build.prop
sed -i -e "s/updater\.ver=.*/updater\.ver=$miversion/" /tmp/build.prop
mv -f /tmp/build.prop /system/build.prop
chmod 644 /system/build.prop
