#!/system/bin/sh
miversion='3.6.5'
mitime='śro, 5 cze 2013, 21:11:11'
miutc='1370459471'
miota='20130605-2111'
cp -f /system/build.prop /tmp/build.prop
chmod 755 /tmp/build.prop
sed -i -e "s/ro\.build\.date=.*/ro\.build\.date=$mitime/" /tmp/build.prop
sed -i -e "s/ro\.build\.date\.utc=.*/ro\.build\.date\.utc=$miutc/" /tmp/build.prop
sed -i -e "s/ro\.build\.version\.incremental=.*/ro\.build\.version\.incremental=$miversion/" /tmp/build.prop
sed -i -e "s/updater\.time=.*/updater\.time=$miota/" /tmp/build.prop
sed -i -e "s/updater\.ver=.*/updater\.ver=$miversion/" /tmp/build.prop
mv -f /tmp/build.prop /system/build.prop
chmod 644 /system/build.prop
