#!/system/bin/sh

#fs tweaks
busybox mount -o remount,noatime,nodiratime,rw,barrier=0,data=writeback /data
busybox mount -o remount,noatime,nodiratime,rw,barrier=0,data=writeback /cache
busybox mount -o remount,noatime,nodiratime,rw /system
busybox mount -o remount,noatime,nodiratime /dev
busybox mount -o remount,noatime,nodiratime /proc
busybox mount -o remount,noatime,nodiratime /sys